### ISSUE TITLE
Allow HTML codes to propagate through 

### ISSUE THREAD

**Issue by dhubbard-ic** [atlassian/commonmark-java#145] opened 2018-12-13 17:46 UTC
As I understand it commonmark-java autoconverts HTML entity references.  My issue is similar to [#50](https://github.com/atlassian/commonmark-java/issues/50) - but that didn't quite provide a way to disable.

I was hoping to include a tick symbol in markdown file (as per [this](https://stackoverflow.com/a/18294705/1265200)) and allow these to appear in rendered HTML.  

However `&#x2714;` gets rendered as `?`.

I have tried setting `HtmlRenderer.builder().escapeHtml(true)` and "false" without success.

Is there a way to disable the convertion?

**Comment by noties** [comment] 2018-12-13 18:02
Hey @dhubbard-ic !

The thing is, most likely, your typeface/device doesn't support this symbol. It has nothing to do with escaping really. If you would like to disable this conversion you will literally get `&#x2714;` and nothing more. I took a screenshot on my emulator and it works in both contexts (markdown and HTML)

![screenshot_1544723944](https://user-images.githubusercontent.com/7278986/49957928-5c71e200-ff1a-11e8-9358-f4aafe4be2a5.png)

**Comment by robinst** [comment] 2018-12-14 00:54
@noties no worries.

`&#x2714;` will get rendered as this Unicode character: https://www.fileformat.info/info/unicode/char/2714/index.htm

If it renders as an `?` instead, the cause is probably one of:

* An encoding problem before it gets rendered
* You don't have the necessary support for that character in the font

Anyway, nothing to do with this library. Closing this.

**Closed by robinst** 2018-12-14 00:54 UTC
