### ISSUE TITLE
Single quote symbol is not replaced with html entity

### ISSUE THREAD

**Issue by jk1** [atlassian/commonmark-java#109] opened 2017-10-16 15:38 UTC
There's even a test for that in HtmlRendererTest

    @Test
    public void textEscaping() {
        String rendered = defaultRenderer().render(parse("escaping: & < > \" '"));
        assertEquals("<p>escaping: &amp; &lt; &gt; &quot; '</p>\n", rendered);
    }

The question is, why single quote symbol is left unescaped? And is there an easy way to get it escaped?

**Comment by robinst** [comment] 2017-10-18 03:55
It matches what commonmark.js (and probably cmark) does: https://github.com/commonmark/commonmark.js/blob/master/lib/common.js#L68

And when we render attributes in HTML we use `"`, so escaping `'` is not strictly necessary. Or is there a situation where it would be?

Why do you want it to be escaped? What you could do is provide your own [HtmlNodeRendererFactory](https://github.com/atlassian/commonmark-java/blob/master/commonmark/src/main/java/org/commonmark/renderer/html/HtmlRenderer.java#L161) and override rendering for `Text` nodes.

**Comment by jk1** [comment] 2017-10-18 06:30
> Why do you want it to be escaped?

To stay compatible with OWASP security guideslines and to avoid injections: https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet#RULE_.231_-_HTML_Escape_Before_Inserting_Untrusted_Data_into_HTML_Element_Content

Let's assume we have a frontend code like this in our imaginary application
````
<input type='text' value='$renderedMarkdown'/>
````
and someone tries to inject the following into markdown
````
' onmouseover='javascript:alert(document.cookie)'
````
It works atm, due to single quote char not being escaped.

> What you could do is provide your own HtmlNodeRendererFactory and override rendering for Text nodes.

Thanks for the suggestion. I'll give it a try and post back shortly.

**Comment by robinst** [comment] 2017-10-18 18:03
Doing something like that would cause you problems even if we escaped `'`. Say if your frontend application did this:

    <input type="text" value="$renderedMarkdown"/>

And the input Markdown was this:

    [a](/) [b](javascript:alert(document.cookie))

Which renders as this:

    <p><a href="/">a</a> <a href="javascript:alert(document.cookie)">b</a></p>

Now insert that into the "frontend", and you'll have some bad stuff happening because the `"` are not escaped. The problem is that the frontend just took some HTML and inserted it into some other HTML. That is not gonna end well unless you do some additional processing. Or did I misunderstand your example?

**Comment by jk1** [comment] 2017-10-18 18:25
Well that's a fair point. A certain amount of sanitizing is indeed to be performed on a frontend side. It still feels kind of inconsistent though, that current implementation escapes symbols like `"` or `<` leaving `'` to an auxiliary markup sanitizer.

Anyway, a custom text renderer seems to fill the gap:
````kotlin
class EscapingTextRenderer(private val context: HtmlNodeRendererContext): NodeRenderer {

    override fun getNodeTypes() = setOf(Text::class.java)

    override fun render(node: Node) {
        val text = (node as Text).literal.split("'")
        render(text.iterator())
    }

    private tailrec fun render(fragments: Iterator<String>){
        context.writer.text(fragments.next())
        if (fragments.hasNext()) {
            context.writer.raw("&#39;")
            render(fragments)
        }
    }
}
````

**Comment by robinst** [comment] 2017-10-19 22:27
I checked what cmark does (the C reference implementation), and it doesn't escape `'` either (the last argument is the `secure` argument):

https://github.com/commonmark/cmark/blob/53ef343a65e3da19d605cfb7e8909004cfac954e/src/html.c#L17-L19

https://github.com/commonmark/cmark/blob/master/src/houdini_html_e.c#L51-L53

I'm gonna keep this issue open for some time to see if anyone else is interested in this.

**Comment by robinst** [comment] 2018-10-05 07:59
Thanks for raising this. I'll close it as I think it's ok to stay consistent with the reference implementations here.

We can always reopen if other people would like to see this changed too.

**Closed by robinst** 2018-10-05 07:59 UTC
